### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by rudygt**
Hi, 

this "sanitize" function is declared but not called, Someone knows if this is intended so we can remove? or if the satinize step should be applied to the data string? 

Thanks.

### CODE REVIEW

**Comment by weinand** [comment]
@rudygt could you please remove the second commit from the PR. Thanks!

**Comment by rudygt** [comment]
@weinand I removed the commit from the pull request, can you give it a look. 
Thanks.

**Comment by weinand** [comment]
@rudygt I have cherry picked this commit since merging your PR would have resulted in a merge conflict. Thanks!

**Comment by rudygt** [comment]
awesome! Thanks @weinand.

**Pull request closed without merging**
