### PR TITLE
fix japanese localization of "closure" from "閉じる" ("close") to "クロージャ" ("closure")

### PR DESCRIPTION
**Pull request by AtsushiSuzuki**
- fix japanese localization of "closure" from "閉じる" ("close") to "クロージャ" ("closure")

### CODE REVIEW

**Comment by weinand** [comment]
@johnliu2016 fyi

**Comment by johnliu2016** [comment]
@lukaschal, please send this to lingual review

[nodeDebug.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fjpn%2Fvscode-node-debug%2Fout%2Fnode%2FnodeDebug.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";scope.closure" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Closure]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[閉じる]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by johnliu2016** [comment]
@AtsushiSuzuki Thanks for suggesting new string, we'll send to localization and fix as appropriate. Microsoft organization owns the loc of this vscode project, you can open loc issues in Microsoft/vscode main repository and your idea will be well tracked.

**Comment by AtsushiSuzuki** [comment]
Thank you.

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@AtsushiSuzuki  Please, is it possible to add ENU screenshot of mentioned dialog ?

**Comment by AtsushiSuzuki** [comment]
en
ja

Is this ok?

**Comment by lukaschal** [comment]
Fixed as suggested.

File: out\node\nodeDebug.nls.resx
ID: ".resx", 0; "scope.closure"
SRC: Closure
TGT: クロージャ

**Comment by lukaschal** [comment]
@AtsushiSuzuki  Please, are you able to close this pull request ? Translation is implemented from localization side.

**Pull request closed without merging**
