### PR TITLE
fix: add skipFiles for node internals by default

### PR DESCRIPTION
**Pull request by connor4312**
Fixes https://github.com/microsoft/vscode/issues/69959

### CODE REVIEW

**Comment by roblourens** [comment]
Also snippets?

**Comment by connor4312** [comment]
`<eval>` scripts? I'm somewhat more hesitant about those, as I know some builds such as `cheap-eval-source-map`-built Webpack bundles put user code into eval'd code. I'll experiment with how those get surfaced today and see what would be reasonable.

**Comment by roblourens** [comment]
I'm talking about these, that I linked in the issue. You can get this as snippets from intellisense in the launch.json: https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L179

**Comment by connor4312** [comment]
Ah, right, apologies, I'll grab those too!

**Comment by connor4312** [comment]
Updated per discussion. I removed the default we applied at runtime, and instead added the default skipFiles value to the base and dynamically generated snippets.

**Pull request merged**
